<a href="https://colab.research.google.com/github/Bhaumik-Mhatre/get-location/blob/main/4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
def sigmoid(x):
  return 1/(1 + пр.ехр(-х))

In [13]:
X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]]) # Inputs
bias = np.ones((X.shape[0], 1))
X = np.hstack((X, bias))
Y = np.array([[-1], [-1], [-1], [1]]) # AND gate outputs
print(X) # To verify the result

[[-1. -1.  1.]
 [-1.  1.  1.]
 [ 1. -1.  1.]
 [ 1.  1.  1.]]


In [14]:
#Initialize weights to zero
weights = np.zeros((3, 1))
learning_rate = 1

In [15]:
#Hebbian Learning Rule
for i in range(len(X)):
  weights += learning_rate * X[i].reshape(3, 1) * Y[i]
  print(f"Iteration {i+1}: Weights {weights.flatten()}")

Iteration 1: Weights [ 1.  1. -1.]
Iteration 2: Weights [ 2.  0. -2.]
Iteration 3: Weights [ 1.  1. -3.]
Iteration 4: Weights [ 2.  2. -2.]


In [16]:
#Print the final weight matrix after the 4th iteration
print("Final Weight Matrix:")
print(weights)

Final Weight Matrix:
[[ 2.]
 [ 2.]
 [-2.]]


In [17]:
#Testing the model using sign function
for itr in range(len(X)):
  weighted_sum = np.dot (X[itr], weights)
  output = np.sign(weighted_sum)
  print(f"Input: {X[itr]} -> Predicted Output: {output}")

Input: [-1. -1.  1.] -> Predicted Output: [-1.]
Input: [-1.  1.  1.] -> Predicted Output: [-1.]
Input: [ 1. -1.  1.] -> Predicted Output: [-1.]
Input: [1. 1. 1.] -> Predicted Output: [1.]
